### ISSUE TITLE
Ksmbd broken

### ISSUE THREAD

**Issue by flood404** [mirror/dd-wrt#449]
This change here messed up the pc version of DD-WRT.

https://svn.dd-wrt.com/changeset/57754

Running full x64 vga build activated.  

When creating any new files on the shared drive with  Windows 11 I get a error of Invalid File Handle.  
In Linux Mint doing the same thing it errors with Bad File Descriptor. 

You can read existing files and copy files off the share drives just can't add any kind of new files to the Samba shared drive.  If you do its always 0 bytes too.    Sp!derman also confirmed this issue.

**Comment by BrainSlayer** [comment]
yes. if you write to external samba shares this happens. this is nothing new and i also dont know the cause. this is upstream issue of ksmbd. the issue is not present in 4.9 kernels but in 6.1/6.6  and it will only happen if you share samba mounts with it. but as i said. the patch you mentioned is pointless. even without it. this issue exists
